### ISSUE TITLE
Optimization suggestion for reducing test initialization time with ParameterizedRobolectricTestRunner

### ISSUE THREAD

**Issue by takahirom** [sergio-sastre/ComposablePreviewScanner#13]
Thanks as always!
I've been using the ComposablePreviewScanner library and noticed that each test takes approximately 1-5 seconds, which significantly increases the total test duration. It seems that ParameterizedRobolectricTestRunner.Parameters is invoked for each test. I found that using a lazy initialization for the previews can optimize performance. Here's a snippet that could potentially be included in the README:

```kotlin
companion object {
  private val previewsCache: List<ComposablePreview<AndroidPreviewInfo>> by lazy {
    val (value, time) = measureTimedValue {
      AndroidComposablePreviewScanner()
        .scanPackageTrees("your.package")
        .getPreviews()
    }
    println("Compose Preview Scanning took $time")
    value
  }

  @JvmStatic
  @ParameterizedRobolectricTestRunner.Parameters
  fun values(): List<ComposablePreview<AndroidPreviewInfo>> {
    return previewsCache
  }
}
```

Would it be possible to consider this approach for inclusion in the documentation to help others improve the performance of their tests?

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by sergio-sastre** [comment]
Definitely! Thanks for taking the time to investigate the source of the issue 🙏

**Comment by sergio-sastre** [comment]
Added to the docu. Thanks!
