### ISSUE TITLE
Could we use minSdk = 21?

### ISSUE THREAD

**Issue by takahirom** [sergio-sastre/ComposablePreviewScanner#14]
This library's minSdk version is 23. In some fields like Android TV, there are still devices running SDK 21. Since this is a testing library, would it be possible to use minSdk 21 if you don't mind?

**Comment by sergio-sastre** [comment]
Sure! There was no real reason to set it to 23, except that Android Studio default options sets it to 23 😅

I’ll release a new version with that fix today evening Berlin time 👍

**Comment by sergio-sastre** [comment]
Resolved in 0.1.3
