### ISSUE TITLE
Automate RobolectricPreviewInfosApplier.applyFor(preview)

### ISSUE THREAD

**Issue by yschimke** [sergio-sastre/ComposablePreviewScanner#6]
Curious if RobolectricPreviewInfosApplier.applyFor(preview) can be automated for Roborazzi?

It seems like it, and it should match so previews match the screenshots.

**Comment by sergio-sastre** [comment]
Yep, it could be, although it’d require adding Roborazzi as a dependency, if I’m not mistaken.

In that case one could add extra modules for the mappers of each screenshot library, similar to what I did for AndroidUiTestingUtils

**Comment by yschimke** [comment]
Your call, just a suggestion. It would be nice if it all worked pretty much out of the box.

Even consider a gradle plugin so the test isn't needed.

**Comment by yschimke** [comment]
Another idea might be to stabilise this API, then integrate *into* the other screenshot tools.  Let them handle gradle and the API bits, instead of making users deal with both.

But my suggestions are cheap, feel free to ignore/close :)

**Comment by yschimke** [comment]
Moved the suggestion to https://github.com/takahirom/roborazzi/issues/415#issuecomment-2186685942, I'd suggest it's more appropriate there.

**Comment by sergio-sastre** [comment]
I’ll close this, since it is already integrated in Roborazzi.
Issues & PRs to support more @Preview parameters should be open in Roborazzi
