### ISSUE TITLE
Split out device settings such as width, height 

### ISSUE THREAD

**Issue by yschimke** [sergio-sastre/ComposablePreviewScanner#7]
```
java.lang.IllegalArgumentException: failed to parse qualifiers 'w-1dp-h-1dp'. See https://developer.android.com/guide/topics/resources/providing-resources.html#QualifierRules for expected format.
	at org.robolectric.res.Qualifiers.parse(Qualifiers.java:35)
	at org.robolectric.res.Qualifiers.parse(Qualifiers.java:28)
	at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:93)
	at org.robolectric.shadows.ShadowDisplayManager.createDisplayInfo(ShadowDisplayManager.java:193)
	at org.robolectric.shadows.ShadowDisplayManager.createDisplayInfo(ShadowDisplayManager.java:162)
	at org.robolectric.shadows.ShadowDisplayManager.changeDisplay(ShadowDisplayManager.java:226)
	at org.robolectric.RuntimeEnvironment.setQualifiers(RuntimeEnvironment.java:197)
```

Because in AndroidComposablePreviewInfoMapper

device="id:wearos_large_round" implies a bunch of other settings, which aren't currently applied.

Seems preferable for the library to handle this, rather than each app adopting.

**Comment by yschimke** [comment]
I ended up applying the qualifiers and then  querying them with InstrumentationRegistry. Perhaps that avoids parsing config files?

**Comment by yschimke** [comment]
Yep, it's similar issue. If 6 is done, I don't need this. Actually for file naming, but can achieve in other ways.

**Comment by sergio-sastre** [comment]
> I ended up applying the qualifiers and then querying them via InstrumentationRegistry. Perhaps that avoids parsing config files?

Interesting. Could you share a code snippet? That would help 😊

**Comment by yschimke** [comment]
closed PR here https://github.com/android/wear-os-samples/pull/1126/files#diff-4b70e4b273d07b2d520241a25769c3b3b36ecb00b427e43e5027bcbc90b9c363

A few relevant things I needed to do

Apply a device clip

```
           recordOptions = RoborazziOptions.RecordOptions(
                applyDeviceCrop = true,
            ),
```

Grab the device string and then apply via known values, because of this issue

```
    fun applyFor(preview: ComposablePreview<AndroidPreviewInfo>) {
        val device = when (preview.previewInfo.device) {
            "id:wearos_large_round" -> RobolectricDeviceQualifiers.WearOSLargeRound
            "id:wearos_small_round" -> RobolectricDeviceQualifiers.WearOSSmallRound
            "id:wearos_square" -> RobolectricDeviceQualifiers.WearOSSquare
            else -> null
        }
        if (device != null) {
            RuntimeEnvironment.setQualifiers(device)
        }
        RuntimeEnvironment.setFontScale(preview.previewInfo.fontScale)
    }
```

Apply and then grab the size and font scale for the filename

```
   @GraphicsMode(GraphicsMode.Mode.NATIVE)
    @Config(sdk = [33])
    @Test
    fun snapshot() {
        println("snapshot " + preview.methodName)
        RobolectricPreviewInfosApplier.applyFor(preview)

        val context = InstrumentationRegistry.getInstrumentation().context
        val width = context.resources.configuration.screenWidthDp

        val fontScale =
            if (preview.previewInfo.fontScale != 1.0f) "_${preview.previewInfo.fontScale}" else ""
        val device = if (context.resources.configuration.isScreenRound) "${width}dp" else "square"
        captureRoboImage(
            filePath = "src/test/screenshots/${this.javaClass.simpleName}_${preview.methodName}_$device$fontScale.png",
            roborazziOptions = RoborazziOptionsMapper.createFor(preview),
        ) {
            AppScaffold {
                preview()
            }
        }
    }
```

**Comment by sergio-sastre** [comment]
> Yep, it's similar issue. If 6 is done, I don't need this. Actually for file naming, but can achieve in other ways.

FYI
For file naming there is already a utility you might benefit from: [AndroidPreviewScreenshotIdBuilder](https://github.com/sergio-sastre/ComposablePreviewScanner/blob/master/android/src/main/java/sergio/sastre/composable/preview/scanner/android/screenshotid/AndroidPreviewScreenshotIdBuilder.kt)

0.1.2 includes some improvements in that component

**Comment by sergio-sastre** [comment]
Done in 0.4.0
